# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: flex
  labels:
    name: postgres
    component: database
    app.kubernetes.io/part-of: flex
spec:
  type: ClusterIP
  selector:
    name: postgres
    component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
