# Superlink - FLWR central orchestrator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superlink
  namespace: flex
  labels:
    name: superlink
    component: superlink
    app.kubernetes.io/part-of: flex
spec:
  replicas: 1
  selector:
    matchLabels:
      name: superlink
      component: superlink
  template:
    metadata:
      labels:
        name: superlink
        component: superlink
    spec:
      nodeSelector:
        node-role: server
      containers:
        - name: superlink
          image: flwr/superlink:1.22.0
          args: ["--insecure"]
          ports:
            - containerPort: 9091
            - containerPort: 9092
            - containerPort: 9093
