apiVersion: v1
kind: Service
metadata:
  name: superlink
  namespace: flex
  labels:
    name: superlink
    app.kubernetes.io/part-of: flex
spec:
  type: ClusterIP
  selector:
    name: superlink
  ports:
    - name: serverappio
      port: 9091
      targetPort: 9091
    - name: fleet
      port: 9092
      targetPort: 9092
    - name: control
      port: 9093
      targetPort: 9093
